require("prototypes.hide")
require("prototypes.icons")
require("prototypes.locale")
require("prototypes.offshore-pumps")
require("prototypes.order")
require("prototypes.recipes")
require("prototypes.tech")
